# Build settings
markdown: kramdown
highlighter: pygments

# Site settings
title: "Antonio Goncalves"
description: > # this means to ignore newlines until "email:"
   Junior Web Developer

email: goncalveusebio@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Antonio Goncalves'
author: 'Antonio Goncalves'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://eusegone.github.io"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/antOGo81
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

 - icon:	facebook
   url:	https://facebook.com/eusebio.goncalves
   desc: Connect with me facebook
   share_url: //www.facebook.com/sharer.php
   share_title: ?t=
   share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/eusegone
    desc:	see my work
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
